name: Java Appium CI

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Mobile Platform (ANDROID or IOS)'
        required: true
        default: 'ANDROID'
      device_names:
        description: 'Comma-separated device names (e.g. Pixel_7_Pro_API_35,Pixel_5_API_30)'
        required: true
        default: 'Pixel_7_Pro_API_35'
      parallel:
        description: 'Max parallel jobs'
        required: false
        default: '1'
      remote_url:
        description: 'Remote URL for Appium/BrowserStack (optional)'
        required: false
        default: ''

jobs:
  set-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          devices="${{ github.event.inputs.device_names }}"
          arr=()
          IFS=',' read -ra ADDR <<< "$devices"
          for d in "${ADDR[@]}"; do arr+=("$d"); done
          json=$(printf '%s\n' "${arr[@]}" | jq -R . | jq -s .)
          echo "matrix=$json" >> $GITHUB_OUTPUT

  build-and-test:
    needs: set-matrix
    runs-on: ubuntu-latest
    strategy:
      matrix:
        device_name: ${{ fromJson(needs.set-matrix.outputs.matrix) }}
      max-parallel: ${{ github.event.inputs.parallel }}
    env:
      PLATFORM: ${{ github.event.inputs.platform }}
      DEVICE_NAME: ${{ matrix.device_name }}
      REMOTE_URL: ${{ github.event.inputs.remote_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build with Maven (skip tests)
        run: mvn clean install -DskipTests

      - name: Run Tests
        run: mvn test
        env:
          PLATFORM: ${{ env.PLATFORM }}
          DEVICE_NAME: ${{ env.DEVICE_NAME }}
          REMOTE_URL: ${{ env.REMOTE_URL }}

      - name: Generate Allure Report
        run: |
          mkdir -p allure-report
          npx allure generate target/allure-results --clean -o allure-report
        continue-on-error: true

      - name: Upload Allure Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: allure-report-web
          path: allure-report
